create table if not exists public.ticket_events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  venue text,
  opens_at timestamptz,
  closes_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'published', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.ticket_windows (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.ticket_events(id) on delete cascade,
  label text not null,
  starts_at timestamptz,
  capacity integer not null default 0 check (capacity >= 0),
  sort_order numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.ticket_reservations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.ticket_events(id) on delete restrict,
  window_id bigint references public.ticket_windows(id) on delete set null,
  reservation_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)),
  customer_name text not null,
  customer_email text not null,
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'reserved' check (status in ('reserved', 'cancelled')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  deleted_at timestamptz
);

create index if not exists ticket_events_public_idx on public.ticket_events (slug, status) where deleted_at is null;
create index if not exists ticket_windows_event_idx on public.ticket_windows (event_id, sort_order) where deleted_at is null;
create index if not exists ticket_reservations_event_idx on public.ticket_reservations (event_id, status) where deleted_at is null;

alter table public.ticket_events enable row level security;
alter table public.ticket_windows enable row level security;
alter table public.ticket_reservations enable row level security;

drop policy if exists "Public can read published ticket events" on public.ticket_events;
create policy "Public can read published ticket events"
  on public.ticket_events for select
  to anon, authenticated
  using (deleted_at is null and status = 'published');

drop policy if exists "Public can read ticket windows" on public.ticket_windows;
create policy "Public can read ticket windows"
  on public.ticket_windows for select
  to anon, authenticated
  using (deleted_at is null and exists (
    select 1 from public.ticket_events e
    where e.id = ticket_windows.event_id
      and e.deleted_at is null
      and e.status = 'published'
  ));

drop policy if exists "Public can create ticket reservations" on public.ticket_reservations;

drop policy if exists "Authenticated can manage ticket events" on public.ticket_events;
create policy "Authenticated can manage ticket events"
  on public.ticket_events for all
  to authenticated
  using (exists (
    select 1 from public.admin_users au
    where au.uuid = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

drop policy if exists "Authenticated can manage ticket windows" on public.ticket_windows;
create policy "Authenticated can manage ticket windows"
  on public.ticket_windows for all
  to authenticated
  using (exists (
    select 1 from public.admin_users au
    where au.uuid = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

drop policy if exists "Authenticated can manage ticket reservations" on public.ticket_reservations;
drop policy if exists "Authenticated admins can read ticket reservations" on public.ticket_reservations;
create policy "Authenticated admins can read ticket reservations"
  on public.ticket_reservations for select
  to authenticated
  using (exists (
    select 1 from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

revoke all on table public.ticket_events from anon, authenticated;
grant select on table public.ticket_events to anon;
grant select, insert, update, delete on table public.ticket_events to authenticated;

revoke all on table public.ticket_windows from anon, authenticated;
grant select on table public.ticket_windows to anon;
grant select, insert, update, delete on table public.ticket_windows to authenticated;

revoke all on table public.ticket_reservations from anon, authenticated;
grant select on table public.ticket_reservations to authenticated;

revoke all on sequence public.ticket_events_id_seq from anon, authenticated;
revoke all on sequence public.ticket_windows_id_seq from anon, authenticated;
revoke all on sequence public.ticket_reservations_id_seq from anon, authenticated;
grant usage, select on sequence public.ticket_events_id_seq to authenticated;
grant usage, select on sequence public.ticket_windows_id_seq to authenticated;
