drop extension if exists "pg_net";


  create table "public"."admin_users" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid,
    "name" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."admin_users" enable row level security;


  create table "public"."archive_urls" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "video_url" text,
    "title" text,
    "image_url" text
      );


alter table "public"."archive_urls" enable row level security;


  create table "public"."credits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "member_id" bigint,
    "credit_title" text,
    "credit_role" text,
    "credit_date" date,
    "deleted_at" timestamp with time zone
      );


alter table "public"."credits" enable row level security;


  create table "public"."members" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "role" text,
    "bio" text,
    "age" integer,
    "height" integer,
    "birthplace" text,
    "join_year" text,
    "hobby" text,
    "skill" text,
    "photoUrl" text,
    "photoUrl_2" text,
    "hurigana" text not null,
    "deleted_at" timestamp with time zone,
    "state_flag" smallint default '8'::smallint
      );


alter table "public"."members" enable row level security;


  create table "public"."site_news" (
    "id" integer generated by default as identity not null,
    "news_title" text,
    "news_summary" text,
    "news_category" text,
    "news_tags" json,
    "news_imageUrl" text,
    "created_at" timestamp with time zone not null default now(),
    "published_at" date,
    "news_status" smallint default '5'::smallint
      );


alter table "public"."site_news" enable row level security;


  create table "public"."update_info" (
    "id" bigint generated by default as identity not null,
    "update_title" text,
    "update_description" text,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "update_date" date default now()
      );


alter table "public"."update_info" enable row level security;

CREATE UNIQUE INDEX admin_users_pkey ON public.admin_users USING btree (id);

CREATE UNIQUE INDEX archive_urls_pkey ON public.archive_urls USING btree (id);

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);

CREATE UNIQUE INDEX site_news_pkey ON public.site_news USING btree (id);

CREATE UNIQUE INDEX todos_pkey ON public.credits USING btree (id);

CREATE UNIQUE INDEX update_info_pkey ON public.update_info USING btree (id);

alter table "public"."admin_users" add constraint "admin_users_pkey" PRIMARY KEY using index "admin_users_pkey";

alter table "public"."archive_urls" add constraint "archive_urls_pkey" PRIMARY KEY using index "archive_urls_pkey";

alter table "public"."credits" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."site_news" add constraint "site_news_pkey" PRIMARY KEY using index "site_news_pkey";

alter table "public"."update_info" add constraint "update_info_pkey" PRIMARY KEY using index "update_info_pkey";

alter table "public"."credits" add constraint "credits_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.members(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."credits" validate constraint "credits_member_id_fkey";

grant delete on table "public"."admin_users" to "anon";

grant insert on table "public"."admin_users" to "anon";

grant references on table "public"."admin_users" to "anon";

grant select on table "public"."admin_users" to "anon";

grant trigger on table "public"."admin_users" to "anon";

grant truncate on table "public"."admin_users" to "anon";

grant update on table "public"."admin_users" to "anon";

grant delete on table "public"."admin_users" to "authenticated";

grant insert on table "public"."admin_users" to "authenticated";

grant references on table "public"."admin_users" to "authenticated";

grant select on table "public"."admin_users" to "authenticated";

grant trigger on table "public"."admin_users" to "authenticated";

grant truncate on table "public"."admin_users" to "authenticated";

grant update on table "public"."admin_users" to "authenticated";

grant delete on table "public"."admin_users" to "service_role";

grant insert on table "public"."admin_users" to "service_role";

grant references on table "public"."admin_users" to "service_role";

grant select on table "public"."admin_users" to "service_role";

grant trigger on table "public"."admin_users" to "service_role";

grant truncate on table "public"."admin_users" to "service_role";

grant update on table "public"."admin_users" to "service_role";

grant delete on table "public"."archive_urls" to "anon";

grant insert on table "public"."archive_urls" to "anon";

grant references on table "public"."archive_urls" to "anon";

grant select on table "public"."archive_urls" to "anon";

grant trigger on table "public"."archive_urls" to "anon";

grant truncate on table "public"."archive_urls" to "anon";

grant update on table "public"."archive_urls" to "anon";

grant delete on table "public"."archive_urls" to "authenticated";

grant insert on table "public"."archive_urls" to "authenticated";

grant references on table "public"."archive_urls" to "authenticated";

grant select on table "public"."archive_urls" to "authenticated";

grant trigger on table "public"."archive_urls" to "authenticated";

grant truncate on table "public"."archive_urls" to "authenticated";

grant update on table "public"."archive_urls" to "authenticated";

grant delete on table "public"."archive_urls" to "service_role";

grant insert on table "public"."archive_urls" to "service_role";

grant references on table "public"."archive_urls" to "service_role";

grant select on table "public"."archive_urls" to "service_role";

grant trigger on table "public"."archive_urls" to "service_role";

grant truncate on table "public"."archive_urls" to "service_role";

grant update on table "public"."archive_urls" to "service_role";

grant delete on table "public"."credits" to "anon";

grant insert on table "public"."credits" to "anon";

grant references on table "public"."credits" to "anon";

grant select on table "public"."credits" to "anon";

grant trigger on table "public"."credits" to "anon";

grant truncate on table "public"."credits" to "anon";

grant update on table "public"."credits" to "anon";

grant delete on table "public"."credits" to "authenticated";

grant insert on table "public"."credits" to "authenticated";

grant references on table "public"."credits" to "authenticated";

grant select on table "public"."credits" to "authenticated";

grant trigger on table "public"."credits" to "authenticated";

grant truncate on table "public"."credits" to "authenticated";

grant update on table "public"."credits" to "authenticated";

grant delete on table "public"."credits" to "service_role";

grant insert on table "public"."credits" to "service_role";

grant references on table "public"."credits" to "service_role";

grant select on table "public"."credits" to "service_role";

grant trigger on table "public"."credits" to "service_role";

grant truncate on table "public"."credits" to "service_role";

grant update on table "public"."credits" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."site_news" to "anon";

grant insert on table "public"."site_news" to "anon";

grant references on table "public"."site_news" to "anon";

grant select on table "public"."site_news" to "anon";

grant trigger on table "public"."site_news" to "anon";

grant truncate on table "public"."site_news" to "anon";

grant update on table "public"."site_news" to "anon";

grant delete on table "public"."site_news" to "authenticated";

grant insert on table "public"."site_news" to "authenticated";

grant references on table "public"."site_news" to "authenticated";

grant select on table "public"."site_news" to "authenticated";

grant trigger on table "public"."site_news" to "authenticated";

grant truncate on table "public"."site_news" to "authenticated";

grant update on table "public"."site_news" to "authenticated";

grant delete on table "public"."site_news" to "service_role";

grant insert on table "public"."site_news" to "service_role";

grant references on table "public"."site_news" to "service_role";

grant select on table "public"."site_news" to "service_role";

grant trigger on table "public"."site_news" to "service_role";

grant truncate on table "public"."site_news" to "service_role";

grant update on table "public"."site_news" to "service_role";

grant delete on table "public"."update_info" to "anon";

grant insert on table "public"."update_info" to "anon";

grant references on table "public"."update_info" to "anon";

grant select on table "public"."update_info" to "anon";

grant trigger on table "public"."update_info" to "anon";

grant truncate on table "public"."update_info" to "anon";

grant update on table "public"."update_info" to "anon";

grant delete on table "public"."update_info" to "authenticated";

grant insert on table "public"."update_info" to "authenticated";

grant references on table "public"."update_info" to "authenticated";

grant select on table "public"."update_info" to "authenticated";

grant trigger on table "public"."update_info" to "authenticated";

grant truncate on table "public"."update_info" to "authenticated";

grant update on table "public"."update_info" to "authenticated";

grant delete on table "public"."update_info" to "service_role";

grant insert on table "public"."update_info" to "service_role";

grant references on table "public"."update_info" to "service_role";

grant select on table "public"."update_info" to "service_role";

grant trigger on table "public"."update_info" to "service_role";

grant truncate on table "public"."update_info" to "service_role";

grant update on table "public"."update_info" to "service_role";


  create policy "Enable read access for mine"
  on "public"."admin_users"
  as permissive
  for select
  to public
using ((uuid = auth.uid()));



  create policy "Enable read access for all users"
  on "public"."archive_urls"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."credits"
  as permissive
  for select
  to public
using (true);



  create policy "Policy with security definer functions"
  on "public"."credits"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))))
with check ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))));



  create policy "Enable read access for all users"
  on "public"."members"
  as permissive
  for select
  to public
using (true);



  create policy "Policy with security definer functions"
  on "public"."members"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))))
with check ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))));



  create policy "Enable read access for all users"
  on "public"."site_news"
  as permissive
  for select
  to public
using (true);



  create policy "Policy with security definer functions"
  on "public"."site_news"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))))
with check ((EXISTS ( SELECT 1
   FROM public.admin_users au
  WHERE (au.uuid = auth.uid()))));



  create policy "Enable read access for all users"
  on "public"."update_info"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


