-- Phase 1: 劇団員費のSquare定期決済連携用データモデル

create table if not exists public.member_billing (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references public.members(id) on update cascade on delete cascade,
  billing_email text,
  registration_token uuid not null default gen_random_uuid() unique,
  registration_attempt_token uuid unique,
  square_customer_id text unique,
  square_subscription_id text unique,
  square_payment_link_id text,
  subscription_status text not null default 'NOT_REGISTERED',
  registration_started_at timestamp with time zone,
  started_at timestamp with time zone,
  last_payment_at timestamp with time zone,
  last_payment_status text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- billing_emailは連絡先であり契約識別子ではないため、一意制約は持たせない。
-- 契約識別はmember_id / registration_attempt_token / Square IDで行う。

create table if not exists public.member_fee_payments (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on update cascade on delete restrict,
  target_month date not null,
  amount integer not null check (amount >= 0),
  currency text not null default 'JPY',
  square_invoice_id text not null unique,
  square_invoice_version integer not null check (square_invoice_version >= 0),
  status text not null,
  paid_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint member_fee_payments_target_month_check
    check (target_month = date_trunc('month', target_month)::date)
);

create index if not exists member_fee_payments_target_month_idx
  on public.member_fee_payments (target_month desc, member_id);

create index if not exists member_fee_payments_member_month_idx
  on public.member_fee_payments (member_id, target_month);

create table if not exists public.square_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'received',
  detail text,
  received_at timestamp with time zone not null default now(),
  processed_at timestamp with time zone
);

-- Webhookの重複排除と、一時エラー後の再送を原子的に扱う。
-- claimed: このリクエストが処理権を取得、busy: 別リクエストが処理中、completed: 処理済み。
create or replace function public.claim_square_webhook_event(
  p_event_id text,
  p_event_type text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_status text;
  current_received_at timestamp with time zone;
begin
  insert into public.square_webhook_events (event_id, event_type, status)
  values (p_event_id, p_event_type, 'received')
  on conflict (event_id) do nothing;

  if found then
    return 'claimed';
  end if;

  select status, received_at
  into current_status, current_received_at
  from public.square_webhook_events
  where event_id = p_event_id
  for update;

  if current_status = 'error'
    or (current_status = 'received' and current_received_at < pg_catalog.now() - interval '5 minutes') then
    update public.square_webhook_events
    set status = 'received',
        event_type = p_event_type,
        detail = null,
        received_at = pg_catalog.now(),
        processed_at = null
    where event_id = p_event_id;
    return 'claimed';
  end if;

  if current_status = 'received' then
    return 'busy';
  end if;

  return 'completed';
end;
$$;

revoke execute on function public.claim_square_webhook_event(text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.claim_square_webhook_event(text, text) to service_role;

-- Checkout発行前にDB行をロックし、同一団員の並行POSTを同じattemptへ束ねる。
-- Square API呼び出しが途中で失敗しても、次回POSTは同じattempt token / idempotency keyで再開する。
create or replace function public.claim_member_fee_registration_attempt(
  p_billing_id bigint,
  p_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  billing_row public.member_billing%rowtype;
  normalized_email text;
  new_attempt_token uuid;
begin
  select *
  into billing_row
  from public.member_billing
  where id = p_billing_id
  for update;

  if not found then
    return pg_catalog.jsonb_build_object('result', 'not_found');
  end if;

  if billing_row.subscription_status = 'PENDING'
    and billing_row.registration_attempt_token is not null then
    return pg_catalog.jsonb_build_object(
      'result', 'pending',
      'attempt_token', billing_row.registration_attempt_token,
      'billing_email', billing_row.billing_email,
      'payment_link_id', billing_row.square_payment_link_id
    );
  end if;

  if billing_row.square_subscription_id is not null
    and billing_row.subscription_status not in ('CANCELED', 'COMPLETED') then
    return pg_catalog.jsonb_build_object(
      'result', 'registered',
      'subscription_status', billing_row.subscription_status
    );
  end if;

  normalized_email := pg_catalog.lower(pg_catalog.btrim(pg_catalog.coalesce(p_email, '')));
  if normalized_email = '' then
    return pg_catalog.jsonb_build_object('result', 'invalid_email');
  end if;

  new_attempt_token := gen_random_uuid();

  update public.member_billing
  set billing_email = normalized_email,
      registration_attempt_token = new_attempt_token,
      square_subscription_id = null,
      square_payment_link_id = null,
      subscription_status = 'PENDING',
      registration_started_at = pg_catalog.now(),
      updated_at = pg_catalog.now()
  where id = p_billing_id;

  return pg_catalog.jsonb_build_object(
    'result', 'claimed',
    'attempt_token', new_attempt_token,
    'billing_email', normalized_email,
    'payment_link_id', null
  );
end;
$$;

revoke execute on function public.claim_member_fee_registration_attempt(bigint, text)
  from public, anon, authenticated, service_role;
grant execute on function public.claim_member_fee_registration_attempt(bigint, text) to service_role;

-- Square Invoiceの現在状態projectionをversion順で反映する。
-- 同一InvoiceのWebhookが並行・逆順で処理されても、古いversionは新しい状態を上書きしない。
create or replace function public.apply_member_fee_invoice_projection(
  p_member_id bigint,
  p_target_month date,
  p_amount integer,
  p_currency text,
  p_square_invoice_id text,
  p_square_invoice_version integer,
  p_status text,
  p_paid_at timestamp with time zone
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  applied_id bigint;
begin
  insert into public.member_fee_payments (
    member_id,
    target_month,
    amount,
    currency,
    square_invoice_id,
    square_invoice_version,
    status,
    paid_at
  ) values (
    p_member_id,
    p_target_month,
    p_amount,
    p_currency,
    p_square_invoice_id,
    p_square_invoice_version,
    p_status,
    p_paid_at
  )
  on conflict (square_invoice_id) do update
  set member_id = excluded.member_id,
      target_month = excluded.target_month,
      amount = excluded.amount,
      currency = excluded.currency,
      square_invoice_version = excluded.square_invoice_version,
      status = excluded.status,
      paid_at = excluded.paid_at,
      updated_at = pg_catalog.now()
  where public.member_fee_payments.square_invoice_version <= excluded.square_invoice_version
  returning id into applied_id;

  return applied_id is not null;
end;
$$;

revoke execute on function public.apply_member_fee_invoice_projection(
  bigint, date, integer, text, text, integer, text, timestamp with time zone
) from public, anon, authenticated, service_role;
grant execute on function public.apply_member_fee_invoice_projection(
  bigint, date, integer, text, text, integer, text, timestamp with time zone
) to service_role;

-- 既存団員へ登録トークンを払い出す。
insert into public.member_billing (member_id)
select m.id
from public.members m
on conflict (member_id) do nothing;

-- 今後追加される団員にも自動で請求管理行を作る。
create or replace function public.ensure_member_billing_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.member_billing (member_id)
  values (new.id)
  on conflict (member_id) do nothing;
  return new;
end;
$$;

revoke execute on function public.ensure_member_billing_row()
  from public, anon, authenticated, service_role;

drop trigger if exists members_ensure_member_billing on public.members;
create trigger members_ensure_member_billing
after insert on public.members
for each row execute function public.ensure_member_billing_row();

alter table public.member_billing enable row level security;
alter table public.member_fee_payments enable row level security;
alter table public.square_webhook_events enable row level security;

-- 課金情報は公開せず、既存admin_usersに登録された管理者だけ閲覧可能にする。
drop policy if exists member_billing_admin_select on public.member_billing;
create policy member_billing_admin_select
on public.member_billing
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  )
);

drop policy if exists member_fee_payments_admin_select on public.member_fee_payments;
create policy member_fee_payments_admin_select
on public.member_fee_payments
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  )
);

drop policy if exists square_webhook_events_admin_select on public.square_webhook_events;
create policy square_webhook_events_admin_select
on public.square_webhook_events
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  )
);

revoke all on table public.member_billing from anon, authenticated;
revoke all on table public.member_fee_payments from anon, authenticated;
revoke all on table public.square_webhook_events from anon, authenticated;
grant select on table public.member_billing to authenticated;
grant select on table public.member_fee_payments to authenticated;
grant select on table public.square_webhook_events to authenticated;

grant all on table public.member_billing to service_role;
grant all on table public.member_fee_payments to service_role;
grant all on table public.square_webhook_events to service_role;

revoke all on sequence public.member_billing_id_seq from anon, authenticated, service_role;
revoke all on sequence public.member_fee_payments_id_seq from anon, authenticated, service_role;
grant usage, select on sequence public.member_billing_id_seq to service_role;
grant usage, select on sequence public.member_fee_payments_id_seq to service_role;