create schema if not exists private;

revoke all on schema private from public, anon, authenticated;

create index if not exists admin_users_uuid_idx
  on public.admin_users (uuid);

create table public.ticket_events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  venue text,
  opens_at timestamptz,
  closes_at timestamptz,
  sanity_performance_id text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint ticket_events_status_check
    check (status in ('draft', 'published', 'closed')),
  constraint ticket_events_slug_path_segment_check
    check (slug ~ '^[A-Za-z0-9_-]+$'),
  constraint ticket_events_title_check
    check (nullif(btrim(title), '') is not null),
  constraint ticket_events_time_order_check
    check (closes_at is null or opens_at is null or closes_at >= opens_at),
  constraint ticket_events_published_sanity_check
    check (
      status not in ('published', 'closed')
      or nullif(btrim(sanity_performance_id), '') is not null
    )
);

create table public.ticket_windows (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.ticket_events(id) on delete cascade,
  label text not null,
  starts_at timestamptz,
  capacity integer not null default 0,
  sort_order numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint ticket_windows_capacity_check
    check (capacity >= 0),
  constraint ticket_windows_label_check
    check (nullif(btrim(label), '') is not null)
);

create table public.ticket_reservations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.ticket_events(id) on delete restrict,
  window_id bigint references public.ticket_windows(id) on delete set null,
  reservation_code text not null unique,
  customer_name text not null,
  customer_email text not null,
  quantity integer not null default 1,
  status text not null default 'reserved',
  note text,
  request_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  deleted_at timestamptz,
  constraint ticket_reservations_quantity_check
    check (quantity > 0),
  constraint ticket_reservations_status_check
    check (status in ('reserved', 'cancelled')),
  constraint ticket_reservations_customer_name_length_check
    check (char_length(customer_name) <= 200),
  constraint ticket_reservations_customer_email_length_check
    check (char_length(customer_email) <= 320),
  constraint ticket_reservations_note_length_check
    check (note is null or char_length(note) <= 2000)
);

create index ticket_events_public_idx
  on public.ticket_events (slug, status)
  where deleted_at is null;

create index ticket_events_sanity_performance_idx
  on public.ticket_events (sanity_performance_id)
  where deleted_at is null;

create index ticket_windows_event_idx
  on public.ticket_windows (event_id, sort_order)
  where deleted_at is null;

create index ticket_reservations_event_idx
  on public.ticket_reservations (event_id, status)
  where deleted_at is null;

create index ticket_reservations_window_active_idx
  on public.ticket_reservations (window_id)
  where deleted_at is null and status = 'reserved';

create unique index ticket_reservations_request_id_idx
  on public.ticket_reservations (request_id)
  where request_id is not null;

alter table public.ticket_events enable row level security;
alter table public.ticket_windows enable row level security;
alter table public.ticket_reservations enable row level security;

create policy "Public can read published ticket events"
  on public.ticket_events for select
  to anon, authenticated
  using (
    deleted_at is null
    and status in ('published', 'closed')
    and nullif(btrim(sanity_performance_id), '') is not null
  );

create policy "Authenticated can manage ticket events"
  on public.ticket_events for all
  to authenticated
  using (exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ))
  with check (exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

create policy "Public can read ticket windows"
  on public.ticket_windows for select
  to anon, authenticated
  using (
    deleted_at is null
    and exists (
      select 1
      from public.ticket_events e
      where e.id = ticket_windows.event_id
        and e.deleted_at is null
        and e.status in ('published', 'closed')
        and nullif(btrim(e.sanity_performance_id), '') is not null
    )
  );

create policy "Authenticated can manage ticket windows"
  on public.ticket_windows for all
  to authenticated
  using (exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ))
  with check (exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

create policy "Authenticated admins can read ticket reservations"
  on public.ticket_reservations for select
  to authenticated
  using (exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ));

revoke all on table public.ticket_events from anon, authenticated;
grant select on table public.ticket_events to anon;
grant select, insert, update, delete on table public.ticket_events to authenticated;

revoke all on table public.ticket_windows from anon, authenticated;
grant select on table public.ticket_windows to anon;
grant select, insert, update on table public.ticket_windows to authenticated;

revoke all on table public.ticket_reservations from anon, authenticated;
grant select on table public.ticket_reservations to authenticated;

revoke all on sequence public.ticket_events_id_seq from anon, authenticated;
revoke all on sequence public.ticket_windows_id_seq from anon, authenticated;
revoke all on sequence public.ticket_reservations_id_seq from anon, authenticated;
grant usage, select on sequence public.ticket_events_id_seq to authenticated;
grant usage, select on sequence public.ticket_windows_id_seq to authenticated;

create or replace function private.set_ticket_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = clock_timestamp();
  return new;
end;
$$;

revoke all on function private.set_ticket_updated_at()
  from public, anon, authenticated;

create trigger ticket_events_updated_at
before update on public.ticket_events
for each row
execute function private.set_ticket_updated_at();

create trigger ticket_windows_updated_at
before update on public.ticket_windows
for each row
execute function private.set_ticket_updated_at();

create or replace function private.generate_ticket_reservation_code()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_code text;
begin
  loop
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_code, 0));

    if not exists (
      select 1
      from public.ticket_reservations r
      where r.reservation_code = v_code
    ) then
      return v_code;
    end if;
  end loop;
end;
$$;

revoke all on function private.generate_ticket_reservation_code()
  from public, anon, authenticated;

alter table public.ticket_reservations
  alter column reservation_code
  set default private.generate_ticket_reservation_code();

create or replace function private.prevent_ticket_window_event_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.event_id is distinct from old.event_id
    and exists (
      select 1
      from public.ticket_reservations r
      where r.window_id = old.id
    )
  then
    raise exception 'Ticket windows with reservations cannot change events'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

revoke all on function private.prevent_ticket_window_event_change()
  from public, anon, authenticated;

create trigger ticket_windows_event_change_guard
before update of event_id on public.ticket_windows
for each row
execute function private.prevent_ticket_window_event_change();

create or replace function private.prevent_ticket_window_mode_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_id bigint;
begin
  if tg_op = 'UPDATE' and new.event_id is not distinct from old.event_id then
    return new;
  end if;

  select e.id
  into v_event_id
  from public.ticket_events e
  where e.id = new.event_id
  for update;

  if not found then
    return new;
  end if;

  if exists (
    select 1
    from public.ticket_reservations r
    where r.event_id = v_event_id
      and r.window_id is null
      and r.deleted_at is null
      and r.status = 'reserved'
  ) then
    raise exception 'Cannot add ticket windows after free-seating reservations'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

revoke all on function private.prevent_ticket_window_mode_change()
  from public, anon, authenticated;

create trigger ticket_windows_mode_change_guard
before insert or update of event_id on public.ticket_windows
for each row
execute function private.prevent_ticket_window_mode_change();

create or replace function private.validate_ticket_window_capacity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_reserved_quantity bigint;
begin
  if new.capacity > 0 then
    select coalesce(sum(r.quantity), 0::bigint)
    into v_reserved_quantity
    from public.ticket_reservations r
    where r.window_id = old.id
      and r.deleted_at is null
      and r.status = 'reserved';

    if v_reserved_quantity > new.capacity then
      raise exception 'Ticket window capacity cannot be lower than active reservations'
        using errcode = 'P0001';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.validate_ticket_window_capacity()
  from public, anon, authenticated;

create trigger ticket_windows_capacity_guard
before update of capacity on public.ticket_windows
for each row
execute function private.validate_ticket_window_capacity();

create or replace function private.create_ticket_reservation(
  p_event_id bigint,
  p_window_id bigint,
  p_customer_name text,
  p_customer_email text,
  p_quantity integer,
  p_note text,
  p_request_id uuid
)
returns table (reservation_code text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event public.ticket_events%rowtype;
  v_window public.ticket_windows%rowtype;
  v_reserved_quantity bigint;
  v_reservation_code text;
  v_now timestamptz;
begin
  if p_request_id is null then
    raise exception 'Ticket reservation request ID is required'
      using errcode = 'P0001';
  end if;

  if p_quantity is null or p_quantity < 1 or p_quantity > 10 then
    raise exception 'Ticket quantity must be between 1 and 10'
      using errcode = 'P0001';
  end if;

  if nullif(btrim(p_customer_name), '') is null then
    raise exception 'Customer name is required'
      using errcode = 'P0001';
  end if;

  if nullif(btrim(p_customer_email), '') is null then
    raise exception 'Customer email is required'
      using errcode = 'P0001';
  end if;

  select r.reservation_code
  into v_reservation_code
  from public.ticket_reservations r
  where r.request_id = p_request_id;

  if found then
    return query select v_reservation_code;
    return;
  end if;

  select e.*
  into v_event
  from public.ticket_events e
  where e.id = p_event_id
  for update;

  if not found then
    raise exception 'Ticket event is not accepting reservations'
      using errcode = 'P0001';
  end if;

  select r.reservation_code
  into v_reservation_code
  from public.ticket_reservations r
  where r.request_id = p_request_id;

  if found then
    return query select v_reservation_code;
    return;
  end if;

  if v_event.deleted_at is not null
    or v_event.status <> 'published'
    or nullif(btrim(v_event.sanity_performance_id), '') is null
  then
    raise exception 'Ticket event is not accepting reservations'
      using errcode = 'P0001';
  end if;

  v_now := clock_timestamp();

  if v_event.opens_at is not null and v_event.opens_at > v_now then
    raise exception 'Ticket reservation is not open'
      using errcode = 'P0001';
  end if;

  if v_event.closes_at is not null and v_event.closes_at < v_now then
    raise exception 'Ticket reservation is closed'
      using errcode = 'P0001';
  end if;

  if p_window_id is null then
    if exists (
      select 1
      from public.ticket_windows w
      where w.event_id = p_event_id
    ) then
      raise exception 'A ticket window is required'
        using errcode = 'P0001';
    end if;
  else
    select w.*
    into v_window
    from public.ticket_windows w
    where w.id = p_window_id
      and w.event_id = p_event_id
      and w.deleted_at is null
    for update;

    if not found then
      raise exception 'Ticket window is unavailable'
        using errcode = 'P0001';
    end if;

    v_now := clock_timestamp();

    if v_event.closes_at is not null and v_event.closes_at < v_now then
      raise exception 'Ticket reservation is closed'
        using errcode = 'P0001';
    end if;

    if v_window.starts_at is not null and v_window.starts_at <= v_now then
      raise exception 'Ticket window has already started'
        using errcode = 'P0001';
    end if;

    if v_window.capacity > 0 then
      select coalesce(sum(r.quantity), 0::bigint)
      into v_reserved_quantity
      from public.ticket_reservations r
      where r.window_id = p_window_id
        and r.deleted_at is null
        and r.status = 'reserved';

      if v_reserved_quantity + p_quantity > v_window.capacity then
        raise exception 'Ticket window does not have enough capacity'
          using errcode = 'P0001';
      end if;
    end if;
  end if;

  insert into public.ticket_reservations (
    event_id,
    window_id,
    customer_name,
    customer_email,
    quantity,
    note,
    request_id
  ) values (
    p_event_id,
    p_window_id,
    btrim(p_customer_name),
    btrim(p_customer_email),
    p_quantity,
    nullif(btrim(p_note), ''),
    p_request_id
  )
  on conflict (request_id) where request_id is not null do nothing
  returning public.ticket_reservations.reservation_code into v_reservation_code;

  if not found then
    select r.reservation_code
    into v_reservation_code
    from public.ticket_reservations r
    where r.request_id = p_request_id;
  end if;

  return query select v_reservation_code;
end;
$$;

revoke all on function private.create_ticket_reservation(
  bigint, bigint, text, text, integer, text, uuid
) from public, anon, authenticated;

create or replace function private.create_ticket_reservation(
  p_event_id bigint,
  p_window_id bigint,
  p_customer_name text,
  p_customer_email text,
  p_quantity integer,
  p_note text default null
)
returns table (reservation_code text)
language sql
security definer
set search_path = ''
as $$
  select *
  from private.create_ticket_reservation(
    p_event_id,
    p_window_id,
    p_customer_name,
    p_customer_email,
    p_quantity,
    p_note,
    gen_random_uuid()
  );
$$;

revoke all on function private.create_ticket_reservation(
  bigint, bigint, text, text, integer, text
) from public, anon, authenticated;

create or replace function public.create_ticket_reservation(
  p_event_id bigint,
  p_window_id bigint,
  p_customer_name text,
  p_customer_email text,
  p_quantity integer,
  p_note text default null
)
returns table (reservation_code text)
language sql
security definer
set search_path = ''
as $$
  select *
  from private.create_ticket_reservation(
    p_event_id,
    p_window_id,
    p_customer_name,
    p_customer_email,
    p_quantity,
    p_note,
    gen_random_uuid()
  );
$$;

revoke all on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, text
) from public;
grant execute on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, text
) to anon, authenticated;

create or replace function public.create_ticket_reservation(
  p_event_id bigint,
  p_window_id bigint,
  p_customer_name text,
  p_customer_email text,
  p_quantity integer,
  p_note text,
  p_request_id uuid
)
returns table (reservation_code text)
language sql
security definer
set search_path = ''
as $$
  select *
  from private.create_ticket_reservation(
    p_event_id,
    p_window_id,
    p_customer_name,
    p_customer_email,
    p_quantity,
    p_note,
    p_request_id
  );
$$;

revoke all on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, text, uuid
) from public;
grant execute on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, text, uuid
) to anon, authenticated;

create or replace function public.create_ticket_reservation(
  p_event_id bigint,
  p_window_id bigint,
  p_customer_name text,
  p_customer_email text,
  p_quantity integer,
  p_request_id uuid
)
returns table (reservation_code text)
language sql
security definer
set search_path = ''
as $$
  select *
  from private.create_ticket_reservation(
    p_event_id,
    p_window_id,
    p_customer_name,
    p_customer_email,
    p_quantity,
    null::text,
    p_request_id
  );
$$;

revoke all on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, uuid
) from public;
grant execute on function public.create_ticket_reservation(
  bigint, bigint, text, text, integer, uuid
) to anon, authenticated;

create or replace function public.get_ticket_window_availability(p_event_id bigint)
returns table (
  window_id bigint,
  capacity integer,
  reserved_quantity bigint,
  remaining_quantity bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    w.id,
    w.capacity,
    coalesce(sum(r.quantity), 0::bigint) as reserved_quantity,
    case
      when w.capacity > 0 then greatest(
        w.capacity::bigint - coalesce(sum(r.quantity), 0::bigint),
        0::bigint
      )
      else null::bigint
    end as remaining_quantity
  from public.ticket_windows w
  join public.ticket_events e
    on e.id = w.event_id
   and e.id = p_event_id
   and e.deleted_at is null
   and e.status in ('published', 'closed')
   and nullif(btrim(e.sanity_performance_id), '') is not null
  left join public.ticket_reservations r
    on r.window_id = w.id
   and r.deleted_at is null
   and r.status = 'reserved'
  where w.deleted_at is null
  group by w.id, w.capacity, w.sort_order
  order by w.sort_order, w.id;
$$;

revoke all on function public.get_ticket_window_availability(bigint)
  from public, anon, authenticated;
grant execute on function public.get_ticket_window_availability(bigint)
  to anon, authenticated;

create or replace function public.get_ticket_event_window_history(p_event_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.ticket_events e
    where e.id = p_event_id
      and e.deleted_at is null
      and e.status in ('published', 'closed')
      and nullif(btrim(e.sanity_performance_id), '') is not null
  )
  and exists (
    select 1
    from public.ticket_windows w
    where w.event_id = p_event_id
  );
$$;

revoke all on function public.get_ticket_event_window_history(bigint)
  from public, anon, authenticated;
grant execute on function public.get_ticket_event_window_history(bigint)
  to anon, authenticated;

create or replace function private.cancel_ticket_reservation(p_reservation_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ) then
    raise exception 'Ticket reservation cancellation requires an administrator'
      using errcode = '42501';
  end if;

  update public.ticket_reservations
  set status = 'cancelled',
      cancelled_at = clock_timestamp(),
      updated_at = clock_timestamp()
  where id = p_reservation_id
    and deleted_at is null
    and status = 'reserved';

  if not found then
    raise exception 'Ticket reservation is unavailable'
      using errcode = 'P0002';
  end if;
end;
$$;

revoke all on function private.cancel_ticket_reservation(bigint)
  from public, anon, authenticated;

create or replace function public.cancel_ticket_reservation(p_reservation_id bigint)
returns void
language sql
security definer
set search_path = ''
as $$
  select private.cancel_ticket_reservation(p_reservation_id);
$$;

revoke all on function public.cancel_ticket_reservation(bigint)
  from public, anon;
grant execute on function public.cancel_ticket_reservation(bigint)
  to authenticated;

create or replace function private.delete_ticket_window(p_window_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ) then
    raise exception 'Ticket window deletion requires an administrator'
      using errcode = '42501';
  end if;

  update public.ticket_windows
  set deleted_at = clock_timestamp(),
      updated_at = clock_timestamp()
  where id = p_window_id
    and deleted_at is null;

  if not found then
    raise exception 'Ticket window is unavailable'
      using errcode = 'P0002';
  end if;
end;
$$;

revoke all on function private.delete_ticket_window(bigint)
  from public, anon, authenticated;

create or replace function public.delete_ticket_window(p_window_id bigint)
returns void
language sql
security definer
set search_path = ''
as $$
  select private.delete_ticket_window(p_window_id);
$$;

revoke all on function public.delete_ticket_window(bigint)
  from public, anon;
grant execute on function public.delete_ticket_window(bigint)
  to authenticated;

create or replace function public.get_ticket_window_reservation_totals()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_totals jsonb;
begin
  if (select auth.uid()) is null or not exists (
    select 1
    from public.admin_users au
    where au.uuid = (select auth.uid())
  ) then
    raise exception 'Ticket reservation totals require an administrator'
      using errcode = '42501';
  end if;

  select coalesce(
    jsonb_object_agg(t.window_id::text, t.reserved_quantity),
    '{}'::jsonb
  )
  into v_totals
  from (
    select
      r.window_id,
      coalesce(sum(r.quantity), 0::bigint) as reserved_quantity
    from public.ticket_reservations r
    where r.window_id is not null
      and r.deleted_at is null
      and r.status = 'reserved'
    group by r.window_id
  ) t;

  return v_totals;
end;
$$;

revoke all on function public.get_ticket_window_reservation_totals()
  from public, anon, authenticated;
grant execute on function public.get_ticket_window_reservation_totals()
  to authenticated;
