-- Phase 1: 劇団員費のSquare定期決済連携用データモデル

create table if not exists public.member_billing (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references public.members(id) on update cascade on delete cascade,
  billing_email text,
  registration_token uuid not null default gen_random_uuid() unique,
  square_customer_id text unique,
  square_subscription_id text unique,
  square_payment_link_id text,
  subscription_status text not null default 'NOT_REGISTERED',
  registration_started_at timestamp with time zone,
  started_at timestamp with time zone,
  last_payment_at timestamp with time zone,
  last_payment_status text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create unique index if not exists member_billing_billing_email_unique_idx
  on public.member_billing (lower(billing_email))
  where billing_email is not null;

create table if not exists public.member_fee_payments (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on update cascade on delete cascade,
  target_month date not null,
  amount integer not null check (amount >= 0),
  currency text not null default 'JPY',
  square_invoice_id text not null unique,
  status text not null,
  paid_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint member_fee_payments_target_month_check
    check (target_month = date_trunc('month', target_month)::date),
  constraint member_fee_payments_member_month_key unique (member_id, target_month)
);

create index if not exists member_fee_payments_target_month_idx
  on public.member_fee_payments (target_month desc, member_id);

create table if not exists public.square_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'received',
  detail text,
  received_at timestamp with time zone not null default now(),
  processed_at timestamp with time zone
);

-- 既存団員へ登録トークンを払い出す。
insert into public.member_billing (member_id)
select m.id
from public.members m
on conflict (member_id) do nothing;

-- 今後追加される団員にも自動で請求管理行を作る。
create or replace function public.ensure_member_billing_row()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.member_billing (member_id)
  values (new.id)
  on conflict (member_id) do nothing;
  return new;
end;
$$;

drop trigger if exists members_ensure_member_billing on public.members;
create trigger members_ensure_member_billing
after insert on public.members
for each row execute function public.ensure_member_billing_row();

alter table public.member_billing enable row level security;
alter table public.member_fee_payments enable row level security;
alter table public.square_webhook_events enable row level security;

-- 課金情報は公開せず、既存admin_usersに登録された管理者だけ閲覧可能にする。
drop policy if exists member_billing_admin_select on public.member_billing;
create policy member_billing_admin_select
on public.member_billing
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = auth.uid()
  )
);

drop policy if exists member_fee_payments_admin_select on public.member_fee_payments;
create policy member_fee_payments_admin_select
on public.member_fee_payments
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = auth.uid()
  )
);

drop policy if exists square_webhook_events_admin_select on public.square_webhook_events;
create policy square_webhook_events_admin_select
on public.square_webhook_events
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users au
    where au.uuid = auth.uid()
  )
);

grant select on table public.member_billing to authenticated;
grant select on table public.member_fee_payments to authenticated;
grant select on table public.square_webhook_events to authenticated;

grant all on table public.member_billing to service_role;
grant all on table public.member_fee_payments to service_role;
grant all on table public.square_webhook_events to service_role;

grant usage, select on sequence public.member_billing_id_seq to service_role;
grant usage, select on sequence public.member_fee_payments_id_seq to service_role;
